[package]
name = "brics"
version = "0.1.47"
edition = "2021"

[dependencies]
bevy = { version = "0.18.0", default-features = false, features = ["bevy_ui", "bevy_core_pipeline", "bevy_render", "bevy_text", "bevy_asset"] }
serde = { version = "1.0", features = ["derive"] }
rand = "0.9"
