[package]
name = "brics"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.13" }
bevy_egui = "0.27"
egui_plot = "0.27"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
jitui = { path = "../jitui" } # Probably needed for schemas initially
